apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-skaffold-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-sample-skaffold
  template:
    metadata:
      labels:
        app: dev-sample-skaffold
    spec:
      containers:
      - name: nginx-container
        image: DOCKERHUB_USER/sample-skaffold
