apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  # ビルドしたDockerイメージの保存先とイメージ名
  - imageName: DOCKERHUB_USER/skaffold-sample
deploy:
  kubectl:
    manifests:
      # 適用するマニフェストのファイル名
      - skaffold-*
