apiVersion: skaffold/v2alpha3
kind: Config
build:
  # ビルドしたDockerイメージの保存先とイメージ名
  artifacts:
  - image: DOCKERHUB_USER/skaffold-sample
    docker:
      dockerfile: ./Dockerfile
  tagPolicy:
    gitCommit: {}
  local:
    push: true
deploy:
  kubectl:
    manifests:
      # 適用するマニフェストのファイル名
      - skaffold-*
