apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  # 빌드한 도커 이미지 저장소와 이미지명
  - imageName: DOCKERHUB_USER/skaffold-sample
  local:
    skipPush: true
deploy:
  kubectl:
    manifests:
      # 적용할 매니페스트 파일명
      - skaffold-*
