apiVersion: apps/v1
kind: Deployment
metadata:
  name: success-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: success-app
  template:
    metadata:
      labels:
        app: success-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.16
