apiVersion: apps/v1
kind: Deployment
metadata:
  name: replace-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: replace-app
  template:
    metadata:
      labels:
        app: replace-app
    spec:
      containers:
      - name: nginx-container
        image: amsy810/echo-nginx:v2.0
