apiVersion: batch/v1
kind: Job
metadata:
  name: sample-single-workqueue-job
spec:
  # 指定しない
  # completions: 1
  parallelism: 1
  backoffLimit: 1
  template:
    metadata:
      name: sleep-job
    spec:
      containers:
      - name: sleep-container
        image: centos:6
        command: ["sleep"]
        args: ["30"]
      restartPolicy: Never
