apiVersion: batch/v1
kind: Job
metadata:
  name: sample-multi-task-job
spec:
  completions: 5
  parallelism: 3
  backoffLimit: 5
  template:
    spec:
      containers:
      - name: tools-container
        image: amsy810/tools:latest
        command: ["sleep"]
        args: ["30"]
      restartPolicy: Never
