apiVersion: batch/v1
kind: Job
metadata:
  name: sample-multi-workqueue-job
spec:
  # 指定しない
  # completions: 1
  parallelism: 3
  backoffLimit: 1
  template:
    metadata:
      name: sleep-job
    spec:
      containers:
      - name: tools-container
        image: amsy810/tools:latest
        command: ["sleep"]
        args: ["30"]
      restartPolicy: Never
