apiVersion: batch/v1
kind: Job
metadata:
  name: sample-paralleljob
spec:
  completions: 10
  parallelism: 2
  backoffLimit: 10
  template:
    metadata:
      name: sleep-job
    spec:
      containers:
      - name: sleep-container
        image: amsy810/tools:latest
        command: ["sleep"]
        args: ["30"]
      restartPolicy: Never
