apiVersion: v1
kind: Pod
metadata:
  name: sample-preset-fail-pod
  labels:
    app: podpreset
spec:
  containers:
  - name: nginx-container
    image: nginx:1.16
    env:
    - name: SAMPLE_ENV
      value: CONFLICT_VALUE
