apiVersion: v1
kind: Pod
metadata:
  name: sample-sysctl-initcontainer
spec:
  initContainers:
  - name: initialize-sysctl
    image: busybox:1.27
    command:
    - /bin/sh
    - -c
    - |
      sysctl -w net.core.somaxconn=12345
    securityContext:
      privileged: true
  containers:
  - name: tools-container
    image: amsy810/tools:v2.0
