apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: sample-podsecuritypolicy
spec:
  privileged: false
  runAsUser:
    rule: RunAsAny
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  allowedHostPaths:
  - pathPrefix: "/etc"
  fsGroup:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  volumes:
  - '*'
