apiVersion: v1
kind: PersistentVolume
metadata:
  name: sample-pv
  labels: # 레이블
    type: gce-pv
    environment: stg
spec:
  capacity: # 용량
    storage: 10Gi
  accessModes: # 접근 모드
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Reclaim Policy
  storageClassName: manual # 스토리지클래스
  # PersistentVolume 플러그인별 설정(GCE 영구 디스크 예)
  gcePersistentDisk:
    pdName: sample-gce-pv
    fsType: ext4
