apiVersion: v1
kind: Pod
metadata:
  name: sample-secret-binary-webserver
spec:
  containers:
  - name: nginx-container
    image: nginx:1.16
    volumeMounts:
    - name: config-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: config-volume
    configMap:
      name: sample-secret-binary
