apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-pvc-resize
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: sample-storageclass-resize
