apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-pvc-provisioner
spec:
  storageClassName: sample-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
