apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sample-csi-storageclass
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-standard
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
