kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sample-pvc
spec:
  selector:
    matchLabels:
      type: gce-pv
    matchExpressions:
      - {key: environment, operator: In, values: [stg]}
  resources:
    requests:
      storage: 4Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
