apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: sample-csi-storageclass
  resources:
    requests:
      storage: 1Gi
