apiVersion: v1
kind: Pod
metadata:
  name: sample-node-affinity-fail
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - nvme
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - gke-k8s-default-pool-9c2aa160-d2pl
  containers:
  - name: nginx-container
    image: nginx:1.16
