apiVersion: v1
kind: Pod
metadata:
  name: sample-tolerations
spec:
  containers:
  - name: nginx-container
    image: nginx:1.16
  tolerations:
  - key: "env"
    operator: "Equal"
    value: "prd"
    effect: "NoSchedule"
