apiVersion: v1
kind: Pod
metadata:
  name: sample-node-affinity-fail
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - nvme
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - gke-k8s-default-pool-c110c2c4-ckp9
  containers:
  - name: nginx-container
    image: nginx:1.12
