apiVersion: v1
kind: Pod
metadata:
  name: sample-tolerations-second
spec:
  containers:
    - name: nginx-container
      image: nginx:1.12
  tolerations:
  - key: "env"
    operator: "Equal"
    value: "prd"
    effect: "NoExecute"
    tolerationSeconds: 45
