apiVersion: v1
kind: Pod
metadata:
  name: sample-besteffort
spec:
  containers:
    - name: nginx-container
      image: nginx:1.12
---
apiVersion: v1
kind: Pod
metadata:
  name: sample-guaranteed
spec:
  containers:
    - name: nginx-container
      image: nginx:1.12
      resources:
        limits:
          cpu: 250m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 256Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: sample-burstable
spec:
  containers:
    - name: nginx-container
      image: nginx:1.12
      resources:
        requests:
          cpu: 500m
        limits:
          cpu: 1500m