apiVersion: v1
kind: Pod
metadata:
  name: sample-qos-burstable
spec:
  containers:
  - name: nginx-container
    image: nginx:1.16
    resources:
      requests:
        cpu: "250m"
      limits:
        cpu: "500m"
