apiVersion: v1
kind: Pod
metadata:
  name: sample-ephemeral-storage
spec:
  containers:
  - name: nginx-container
    image: nginx:1.16
    resources:
      requests:
        ephemeral-storage: "1024Mi"
      limits:
        ephemeral-storage: "2048Mi"
