apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: sample-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-vpa-deployment
  updatePolicy:
    updateMode: Auto # Requests更新時にPodの再作成を行う
  resourcePolicy:
    containerPolicies:
    - containerName: no-vpa-container
      mode: "Off" # オートスケール対象外
    - containerName: "*" # 指定していない残りすべてのコンテナ
      mode: Auto # オートスケール対象
      minAllowed:
        memory: 300Mi
      maxAllowed:
        memory: 1000Mi
      controlledResources: ["cpu", "memory"]
