apiVersion: v1
kind: ResourceQuota
metadata:
  name: sample-resourcequota-count-old
  namespace: default
spec:
  hard:
    # 생성 가능한 리소스 수 (구방식)
    # count/*의 신방식에서는 지정 불가
    sample-storageclass.storageclass.storage.k8s.io/persistentvolumeclaims: 10
    services.loadbalancers: 10
    services.nodeports: 10

    # count/*의 신방식으로도 지정 가능
    pods: 10
    persistentvolumeclaims: 10
    replicationcontrollers: 10
    secrets: 10
    configmaps: 10
    services: 10
    resourcequotas: 10
