# Stage 1のコンテナ（アプリケーションをビルド）
FROM golang:1.14.1-alpine3.11 as builder
COPY ./main.go ./
RUN go build -o /go-app ./main.go

# Stage 2のコンテナ（ビルドしたバイナリを内包した実行用コンテナを作成）
FROM alpine:3.11
# Stage 1でビルドした成果物をコピー
COPY --from=builder /go-app .
ENTRYPOINT ["./go-app"]
