---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sample-publish-notready
spec:
  serviceName: sample-publish-notready
  replicas: 3
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: publish-notready
  template:
    metadata:
      labels:
        app: publish-notready
    spec:
      containers:
      - name: nginx-container
        image: amsy810/echo-nginx:v2.0
        readinessProbe:
          exec:
            command: ["sh", "-c", "exit 1"]
---
apiVersion: v1
kind: Service
metadata:
  name: sample-publish-notready
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 8080
    targetPort: 80
  selector:
    app: publish-notready
