apiVersion: v1
kind: Pod
metadata:
  name: sample-restart-never
spec:
  restartPolicy: Never
  containers:
    - name: nginx-container
      image: nginx:1.12
      command: ["sh", "-c", "exit 0"] # 성공의 경우
#      command: ["sh", "-c", "exit 1"] # 실패의 경우
