apiVersion: v1
kind: Pod
metadata:
  name: sample-lifecycle-httpget
spec:
  containers:
  - name: nginx-container
    image: nginx:1.16
    lifecycle:
      postStart:
        httpGet:
          path: /index.html
          port: 80
          scheme: HTTP
