apiVersion: v1
kind: Pod
metadata:
  name: sample-startup
spec:
  containers:
  - name: tools-container
    image: amsy810/tools:v2.0
    livenessProbe:
      exec:
        command: ["sh", "-c", "echo [$(date)] liveness >> /root/log; test ! -e /root/liveness"]
      periodSeconds: 3
    readinessProbe:
      exec:
        command: ["sh", "-c", "echo [$(date)] readiness >> /root/log; test ! -e /root/readiness"]
      periodSeconds: 3
    startupProbe:
      exec:
        command: ["sh", "-c", "echo [$(date)] startup >> /root/log; test -e /root/startup"]
      failureThreshold: 100
      periodSeconds: 3
