apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-csi-hostpath-pvc
spec:
  storageClassName: sample-csi-hostpath-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
