apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: sample-pod-disruption-budget-percentage
spec:
  minAvailable: 90%
  # または
  # maxUnavailable: 10%
  selector:
    matchLabels:
      app: sample-app
