apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: sample-pod-disruption-budget
spec:
  minAvailable: 1
  # ссс
  # maxUnavailable: 1
  selector:
    matchLabels:
      app: sample-app
