apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: sample-pod-disruption-budget-fail
spec:
  minAvailable: 1
  maxUnavailable: 1
  selector:
    matchLabels:
      app: sample-app
