apiVersion: spanner.cnrm.cloud.google.com/v1beta1
kind: SpannerInstance
metadata:
  labels:
    label-one: spannerinstance-sample
  name: spannerinstance-sample
spec:
  config: regional-asia-northeast3
  displayName: My Spanner Instance
  numNodes: 1
---
apiVersion: spanner.cnrm.cloud.google.com/v1beta1
kind: SpannerDatabase
metadata:
  name: spannerdatabase-sample
spec:
  instanceRef:
    name: spannerinstance-sample
  ddl:
  - "CREATE TABLE t1 (t1 INT64 NOT NULL,) PRIMARY KEY(t1)"