apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: sample-cloudsql-sb
  namespace: default
spec:
  instanceRef:
    name: sample-cloudsql-si
  secretName: sample-cloudsql-credential
  parameters:
    roles:
      - roles/cloudsql.client
    serviceAccount: sample-iam
